<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY3tWZBi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY3tWZBi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY3tWZBi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY3tWZBi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY3tWZBi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y3tWZBi',
    'container.build_id' => 'cbf635ad',
    'container.build_time' => 1648420975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY3tWZBi');
